PROYECTODAS/PROYECTODAS/Controllers/CarreraActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROYECTODAS.Models;
using System.Net.Http;

namespace PROYECTODAS.Controllers
{
    public class CarreraActionController : Controller
    {
        // GET: CarreraAction
        public ActionResult ListadoCarreras(string search)
        {
            IEnumerable<carrera> ocarrera = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/CarreraCrud");

            var consumeapi = hc.GetAsync("CarreraCrud?search=" + search);
            consumeapi.Wait();

            var readdata = consumeapi.Result;
            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<IList<carrera>>();
                displaydata.Wait();

                ocarrera = displaydata.Result;
            }
            return View(ocarrera);
        }

        //mostrar pagina CREATE donde se crea una nueva carrera
        public ActionResult Create()
        {
            return View();
        }

        //crear una carrera en pagina CREATE
        [HttpPost]
        public ActionResult Create(carrera insertcarrera)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/CarreraCrud");

            var insertrecord = hc.PostAsJsonAsync<carrera>("CarreraCrud", insertcarrera);
            insertrecord.Wait();

            var guardardata = insertrecord.Result;
            if (guardardata.IsSuccessStatusCode)
            {
                return RedirectToAction("ListadoCarreras");
            }

            return View("Create");
        }

        //ver detalles de una carrera seleccionada
        public ActionResult Detalles(int id)
        {
            CarreraClass ocarrera = null;

            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/");

            var consumeapi = hc.GetAsync("CarreraCrud?id=" + id.ToString());
            consumeapi.Wait();

            var readdata = consumeapi.Result;
            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<CarreraClass>();
                displaydata.Wait();
                ocarrera = displaydata.Result;
            }

            return View(ocarrera);
        }

        //mostrar datos actuales de la carrera en pagina de editar
        public ActionResult Editar(int id)
        {
            CarreraClass ocarrera = null;

            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/");

            var consumeapi = hc.GetAsync("CarreraCrud?id=" + id.ToString());
            consumeapi.Wait();

            var readdata = consumeapi.Result;
            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<CarreraClass>();
                displaydata.Wait();
                ocarrera = displaydata.Result;
            }

            return View(ocarrera);
        }

        //editar y guardar los nuevos datos de carrera
        [HttpPost]
        public ActionResult Editar(CarreraClass cc)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/CarreraCrud");

            var insertrecord = hc.PutAsJsonAsync<CarreraClass>("CarreraCrud", cc);
            insertrecord.Wait();

            var guardardata = insertrecord.Result;
            if (guardardata.IsSuccessStatusCode)
            {
                return RedirectToAction("ListadoCarreras");
            }
            else
            {
                ViewBag.message = "Error en actualizar los datos de la carrera";
            }

            return View(cc);
        }

        //borrar una carrera de la lista
        public ActionResult Delete(int id)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/CarreraCrud");

            var delrecord = hc.DeleteAsync("CarreraCrud/" + id.ToString());
            delrecord.Wait();

            var displaydata = delrecord.Result;
            if (displaydata.IsSuccessStatusCode)
            {
                return RedirectToAction("ListadoCarreras");
            }

            return View("ListadoCarreras");
        }

    }
}

PROYECTODAS/PROYECTODAS/Views/CarreraAction/Create.cshtml
@model PROYECTODAS.carrera

@{
    ViewBag.Title = "Create";
}

<h2>Crear nueva carrera</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>carrera</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.campus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.campus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.campus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.duracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a Carreras", "ListadoCarreras")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROYECTODAS/PROYECTODAS/Views/CarreraAction/Detalles.cshtml
@model PROYECTODAS.Models.CarreraClass

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>CarreraClass</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Campus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Campus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duracion) años
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duracion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    @Html.ActionLink("Regresar a carreras", "ListadoCarreras")
</p>

PROYECTODAS/PROYECTODAS/Views/CarreraAction/Editar.cshtml
@model PROYECTODAS.Models.CarreraClass

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CarreraClass</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Campus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Campus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Campus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a Carreras", "ListadoCarreras")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROYECTODAS/PROYECTODAS/Views/CarreraAction/ListadoCarreras.cshtml
@model IEnumerable<PROYECTODAS.carrera>

@{
    ViewBag.Title = "ListadoCarreras";
}

<h2>¡Carreras para ofrecerte!</h2>

<p>
    @Html.ActionLink("Crear nueva", "Create")
</p>
<br>
<center>
    @using (Html.BeginForm("ListadoCarreras", "CarreraAction", FormMethod.Get))
    {
        <span>Escriba el campus : </span><input type="text" name="search" placeholder="campus" />
        <input type="submit" value="Buscar" name="submit" />
    }
</center>
<br>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.campus)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.campus)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.id }) |
                @Html.ActionLink("Detalles", "Detalles", new { id = item.id }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>