PROYECTODAS/PROYECTODAS/Controllers/ConsultaActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROYECTODAS.Models;
using System.Net.Http;

namespace PROYECTODAS.Controllers
{
    public class ConsultaActionController : Controller
    {
        // GET: ConsultaAction
        public ActionResult Formulario()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Formulario(ConsultaClass consulta)
        {
            if(ModelState.IsValid)
            {
                HttpClient hc = new HttpClient();
                hc.BaseAddress = new Uri("https://localhost:44316/api/ConsultaCrud");

                var insertrec = hc.PostAsJsonAsync<ConsultaClass>("ConsultaCrud", consulta);
                insertrec.Wait();

                var guardarrec = insertrec.Result;
                if (guardarrec.IsSuccessStatusCode)
                {
                    ViewBag.message = "Gracias " + consulta.Nombre + " por tu mensaje, te contactaremos pronto!";
                }

                ModelState.Clear();

            }
            return View();
        }
    }
}

PROYECTODAS/PROYECTODAS/Controllers/NoticiaActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROYECTODAS.Models;
using System.Net.Http;

namespace PROYECTODAS.Controllers
{
    public class NoticiaActionController : Controller
    {
        // GET: NoticiaAction
        public ActionResult Index()
        {
            IEnumerable<noticia> noticiaObj = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/NoticiaCrud");

            var consumeapi = hc.GetAsync("NoticiaCrud");
            consumeapi.Wait();

            var readdata = consumeapi.Result;
            if(readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<IList<noticia>>();
                displaydata.Wait();

                noticiaObj = displaydata.Result;
            }
            
            return View(noticiaObj);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(noticia insertnoticia)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/NoticiaCrud");

            var insertrecord = hc.PostAsJsonAsync<noticia>("NoticiaCrud", insertnoticia);
            insertrecord.Wait();

            var guardardata = insertrecord.Result;
            if(guardardata.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Create");
        }

        //ver detalles de una noticia seleccionada
        public ActionResult Detalles(int id)
        {
            NoticiaClass onoticia = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/NoticiaCrud");

            var consumeapi = hc.GetAsync("NoticiaCrud?id=" + id.ToString());
            consumeapi.Wait();

            var readdata = consumeapi.Result;
            if(readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<NoticiaClass>();
                displaydata.Wait();
                onoticia = displaydata.Result;
            }

            return View(onoticia);
        }

        //mostrar pagina de editar
        public ActionResult Editar(int id)
        {
            NoticiaClass onoticia = null;
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/");

            var consumeapi = hc.GetAsync("NoticiaCrud?id=" + id.ToString());
            consumeapi.Wait();

            var readdata = consumeapi.Result;
            if (readdata.IsSuccessStatusCode)
            {
                var displaydata = readdata.Content.ReadAsAsync<NoticiaClass>();
                displaydata.Wait();
                onoticia = displaydata.Result;
            }

            return View(onoticia);
        }

        //guardar editación
        [HttpPost]
        public ActionResult Editar(NoticiaClass nc)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/NoticiaCrud");

            var insertrecord = hc.PutAsJsonAsync<NoticiaClass>("NoticiaCrud", nc);
            insertrecord.Wait();

            var guardardata = insertrecord.Result;
            if (guardardata.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.message = "Error en actualizar los datos de la noticia";
            }

            return View(nc);

        }

        //borrar noticia
        public ActionResult Delete(int id)
        {
            HttpClient hc = new HttpClient();
            hc.BaseAddress = new Uri("https://localhost:44316/api/NoticiaCrud");

            var delrecord = hc.DeleteAsync("NoticiaCrud/" + id.ToString());
            delrecord.Wait();

            var displaydata = delrecord.Result;
            if (displaydata.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            return View("Index");
        }
    }
}

PROYECTODAS/PROYECTODAS/Views/ConsultaAction/Formulario.cshtml
@model PROYECTODAS.consulta


<center>
    <h2>¡Contactanos!</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.apellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.mensaje, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.mensaje, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.mensaje, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enviar consulta" class="btn btn-default" />
        </div>
    </div>
    <h2>@ViewBag.message</h2>
    </div>
    }
</center>



<div>
    @Html.ActionLink("Regresar a Inicio", "Index", "NoticiaAction")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}